services:
  data-analysis-service:
    container_name: data_analysis_container
    build:
      context: ../jobyte-data-analysis
      dockerfile: Dockerfile
    env_file:
      - ../jobyte-data-analysis/.env
    environment:
      - POSTGRES_HOST=postgres-api-service
    ports:
      - "5000:5000"
    networks:
      - jobyte-network

  postgres-api-service:
    container_name: postgres_api_container
    build:
      context: ./jobyte-api/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=jobyte_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_api_volume:/var/lib/postgresql/data
    networks:
      - jobyte-network

  postgres-keycloak-service:
    container_name: postgres_keycloak_container
    build:
      context: ./jobyte-api/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_volume:/var/lib/postgresql/data
    networks:
      - jobyte-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-service:
    container_name: keycloak_container
    build:
      context: ./jobyte-api/keycloak
      dockerfile: Dockerfile
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    restart: always
    networks:
      - jobyte-network
    depends_on:
      postgres-keycloak-service:
        condition: service_healthy

networks:
  jobyte-network:
    driver: bridge

volumes:
  postgres_api_volume:
  postgres_keycloak_volume: