spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jobyte_db}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/jobyte-realm}

keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:jobyte-realm}
  admin-client:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:jobyte-api}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:395666KnbWTgS1rJeQvKPeKyS7O8nsIc}
    grant-type: client_credentials